### PR TITLE
feat #2: added database support

### PR DESCRIPTION
**Pull request by matthiashermsen**
## Referenced issue

Which issue is referenced by this pull request?

The pull request references #2 

## Checklist

Please check if your pull request fulfills the following requirements:

- [x] The pull request follows the guidelines: https://github.com/matthiashermsen/dotnet-backend/blob/main/CONTRIBUTING.md
- [x] Tests for the changes have been added (for features)

## Type

What kind of change does this pull request introduce? Please check the one that applies to this pull request:

- [ ] Bug fix
- [x] Feature
- [ ] Code style update
- [ ] Refactoring (no functional changes)
- [ ] Build related changes

## Impact

Does this pull request introduce a breaking change? If yes, please describe:

N/A

### CODE REVIEW

**Review by ChaosTh3ori3 — APPROVED** [review]
Is confirmed

**Review by ChaosTh3ori3 — APPROVED** [review]

**Comment by ChaosTh3ori3** [comment]
> Looks nice excited to try it out

**Comment by Judge84** [comment]
I think it will be all right, we will see ;-)

**Review by Judge84 — APPROVED** [review]
we will see

**Review by Raysix93 — APPROVED** [review]
Looking Good

**Comment by ChaosTh3ori3** [comment]
> Is confirmed

**Pull request merged**
